apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: true

  - name: zipkin
    type: zipkin
    access: proxy
    url: http://zipkin:9411
    version: 1
    editable: true