spring:
  application:
    name: gateway
    output:
      ansi:
        enabled: ALWAYS
  lifecycle:
    timeout-per-shutdown-phase: 20s
  cloud:
    gateway:
      default-filters:
        - name: Retry
          args:
            retries: 3
            series: SERVER_ERROR
            methods: GET,POST,PUT,DELETE
            backoff:
              firstBackoff: 50ms
              maxBackoff: 400ms
              factor: 2
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      httpclient:
        connect-timeout: 500
        response-timeout: 5s
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "*"
      routes:
        - id: userservice
          uri: lb://USERSERVICE:8081/
          predicates:
            - Path=/userservice/**
          filters:
            - RewritePath=/userservice/?(?<segment>.*), /$\{segment}
        - id: postservice
          uri: lb://POSTSERVICE:8082/
          predicates:
            - Path=/postservice/**
          filters:
            - RewritePath=/postservice/?(?<segment>.*), /$\{segment}
        - id: notificationservice
          uri: lb://NOTIFICATIONSERVICE:8083/
          predicates:
            - Path=/notificationservice/**
          filters:
            - RewritePath=/notificationservice/?(?<segment>.*), /$\{segment}
        - id: feedservice
          uri: lb://FEEDSERVICE:8085/
          predicates:
            - Path=/feedservice/**
          filters:
            - RewritePath=/feedservice/?(?<segment>.*), /$\{segment}
  docker:
    compose:
      enabled: true
      file: docker/infrastructure-compose.yml
      lifecycle-management: start-only
  threads:
    virtual:
      enabled: true

server:
  forward-headers-strategy: framework
  port: 8080
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: "*"
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URI:http://localhost:9411/}api/v2/spans
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
