include:
  - infrastructure-compose.yml

services:
  userservice:
    image: ghcr.io/tobias-pe/microservices_energyefficiency/userservice:latest
    environment:
      - EUREKA_URI=http://servicediscovery:8761/eureka
      - ZIPKIN_URI=http://zipkin:9411/
      - POSTGRES_URI=jdbc:postgresql://postgres:5432/
      - THC_PATH=/actuator/health
      - THC_PORT=8081
    deploy:
      mode: replicated
      replicas: 2
    healthcheck:
      test: ["CMD", "/cnb/process/health-check"]

  gateway:
    image: ghcr.io/tobias-pe/microservices_energyefficiency/gateway:latest
    ports:
      - "8080:8080"
    labels:
      - kompose.service.type=loadbalancer
    environment:
      - EUREKA_URI=http://servicediscovery:8761/eureka
      - ZIPKIN_URI=http://zipkin:9411/
      - THC_PATH=/actuator/health
      - THC_PORT=8080
    healthcheck:
      test: ["CMD", "/cnb/process/health-check"]


  servicediscovery:
    image: ghcr.io/tobias-pe/microservices_energyefficiency/servicediscovery:latest
    environment:
      - ZIPKIN_URI=http://zipkin:9411/
      - THC_PATH=/actuator/health
      - THC_PORT=8761
    labels:
      - kompose.service.type=loadbalancer
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "/cnb/process/health-check"]