include:
  - infrastructure-compose.yml

services:
  userservice:
    image: ghcr.io/tobias-pe/distributed-systems-energy-efficiency/userservice:latest
    labels:
      - kompose.image-pull-policy=Always
      - kompose.hpa.cpu=70
      - kompose.hpa.memory=65
      - kompose.hpa.replicas.max=5
      - kompose.hpa.replicas.min=2
      - kompose.service.healthcheck.liveness.http_get_port=8081
      - kompose.service.healthcheck.liveness.http_get_path=/actuator/health/liveness
      - kompose.service.healthcheck.readiness.http_get_port=8081
      - kompose.service.healthcheck.readiness.http_get_path=/actuator/health/readiness
      - kompose.service.healthcheck.readiness.start_period=8s
      - kompose.service.healthcheck.readiness.retries=3
      - kompose.service.healthcheck.readiness.timeout=5s
    environment:
      - EUREKA_URI=http://servicediscovery:8761/eureka
      - ZIPKIN_URI=http://zipkin:9411/
      - RABBITMQ_HOST=rabbitmq
      - POSTGRES_URI=jdbc:postgresql://userservice-db:5432/
      - JAVA_TOOL_OPTIONS=-XX:ActiveProcessorCount=4 -XX:MaxDirectMemorySize=100M  #https://github.com/paketo-buildpacks/spring-boot/issues/11
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          memory: 1000M
        reservations:
          cpus: '0.5'
          memory: 1000M
    healthcheck: # without test --> will be provided by kompose.service.healthcheck.liveness
      start_period: 8s
      timeout: 10s
      retries: 5
    stop_grace_period: 30s

  postservice:
    image: ghcr.io/tobias-pe/distributed-systems-energy-efficiency/postservice:latest
    labels:
      - kompose.image-pull-policy=Always
      - kompose.hpa.cpu=70
      - kompose.hpa.memory=70
      - kompose.hpa.replicas.max=12
      - kompose.hpa.replicas.min=2
      - kompose.service.healthcheck.liveness.http_get_port=8082
      - kompose.service.healthcheck.liveness.http_get_path=/actuator/health/liveness
      - kompose.service.healthcheck.readiness.http_get_port=8082
      - kompose.service.healthcheck.readiness.http_get_path=/actuator/health/readiness
      - kompose.service.healthcheck.readiness.start_period=8s
      - kompose.service.healthcheck.readiness.retries=3
      - kompose.service.healthcheck.readiness.timeout=5s
    environment:
      - EUREKA_URI=http://servicediscovery:8761/eureka
      - ZIPKIN_URI=http://zipkin:9411/
      - RABBITMQ_HOST=rabbitmq
      - POSTGRES_URI=jdbc:postgresql://postservice-db:5433/
      - JAVA_TOOL_OPTIONS=-XX:ActiveProcessorCount=4 -XX:MaxDirectMemorySize=100M  #https://github.com/paketo-buildpacks/spring-boot/issues/11
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          memory: 1200M
        reservations:
          cpus: '0.55'
          memory: 1200M
    healthcheck: # without test --> will be provided by kompose.service.healthcheck.liveness
      start_period: 8s
      timeout: 10s
      retries: 5
    stop_grace_period: 30s

  notificationservice:
    image: ghcr.io/tobias-pe/distributed-systems-energy-efficiency/notificationservice:latest
    labels:
      - kompose.image-pull-policy=Always
      - kompose.hpa.cpu=70
      - kompose.hpa.memory=80
      - kompose.hpa.replicas.max=5
      - kompose.hpa.replicas.min=2
      - kompose.service.healthcheck.liveness.http_get_port=8083
      - kompose.service.healthcheck.liveness.http_get_path=/actuator/health/liveness
      - kompose.service.healthcheck.readiness.http_get_port=8083
      - kompose.service.healthcheck.readiness.http_get_path=/actuator/health/readiness
      - kompose.service.healthcheck.readiness.start_period=8s
      - kompose.service.healthcheck.readiness.retries=3
      - kompose.service.healthcheck.readiness.timeout=5s
      - kompose.volume.type=emptyDir
    environment:
      - EUREKA_URI=http://servicediscovery:8761/eureka
      - ZIPKIN_URI=http://zipkin:9411/
      - RABBITMQ_HOST=rabbitmq
      - POSTGRES_URI=jdbc:postgresql://notificationservice-db:5434/
      - JAVA_TOOL_OPTIONS=-XX:ActiveProcessorCount=4 -XX:MaxDirectMemorySize=100M
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          memory: 1000M
        reservations:
          cpus: '0.5'
          memory: 1000M
    healthcheck: # without test --> will be provided by kompose.service.healthcheck.liveness
      start_period: 8s
      timeout: 10s
      retries: 5
    volumes:
      - /workspace/notificationservice
    stop_grace_period: 30s

  statisticservice:
    image: ghcr.io/tobias-pe/distributed-systems-energy-efficiency/statisticservice:latest
    labels:
      - kompose.image-pull-policy=Always
      - kompose.hpa.cpu=70
      - kompose.hpa.memory=80
      - kompose.hpa.replicas.max=12
      - kompose.hpa.replicas.min=2
      - kompose.service.healthcheck.liveness.http_get_port=8084
      - kompose.service.healthcheck.liveness.http_get_path=/actuator/health/liveness
      - kompose.service.healthcheck.readiness.http_get_port=8084
      - kompose.service.healthcheck.readiness.http_get_path=/actuator/health/readiness
      - kompose.service.healthcheck.readiness.start_period=8s
      - kompose.service.healthcheck.readiness.retries=3
      - kompose.service.healthcheck.readiness.timeout=5s
    environment:
      - EUREKA_URI=http://servicediscovery:8761/eureka
      - ZIPKIN_URI=http://zipkin:9411/
      - RABBITMQ_HOST=rabbitmq
      - POSTGRES_URI=jdbc:postgresql://statisticservice-db:5435/
      - JAVA_TOOL_OPTIONS=-XX:ActiveProcessorCount=4 -XX:MaxDirectMemorySize=100M  #https://github.com/paketo-buildpacks/spring-boot/issues/11
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          memory: 1000M
        reservations:
          cpus: '0.5'
          memory: 1000M
    healthcheck: # without test --> will be provided by kompose.service.healthcheck.liveness
      start_period: 8s
      timeout: 10s
      retries: 5
    stop_grace_period: 30s

  feedservice:
    image: ghcr.io/tobias-pe/distributed-systems-energy-efficiency/feedservice:latest
    labels:
      - kompose.image-pull-policy=Always
      - kompose.hpa.cpu=70
      - kompose.hpa.memory=70
      - kompose.hpa.replicas.max=12
      - kompose.hpa.replicas.min=2
      - kompose.service.healthcheck.liveness.http_get_port=8085
      - kompose.service.healthcheck.liveness.http_get_path=/actuator/health/liveness
      - kompose.service.healthcheck.readiness.http_get_port=8085
      - kompose.service.healthcheck.readiness.http_get_path=/actuator/health/readiness
      - kompose.service.healthcheck.readiness.start_period=8s
      - kompose.service.healthcheck.readiness.retries=3
      - kompose.service.healthcheck.readiness.timeout=5s
    environment:
      - EUREKA_URI=http://servicediscovery:8761/eureka
      - ZIPKIN_URI=http://zipkin:9411/
      - RABBITMQ_HOST=rabbitmq
      - REDIS_URI=redis
      - POSTGRES_URI=jdbc:postgresql://feedservice-db:5436/
      - JAVA_TOOL_OPTIONS=-XX:ActiveProcessorCount=4 -XX:MaxDirectMemorySize=100M  #https://github.com/paketo-buildpacks/spring-boot/issues/11
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          memory: 1200M
        reservations:
          cpus: '0.55'
          memory: 1200M
    healthcheck: # without test --> will be provided by kompose.service.healthcheck.liveness
      start_period: 8s
      timeout: 10s
      retries: 5
    stop_grace_period: 30s

  gateway:
    image: ghcr.io/tobias-pe/distributed-systems-energy-efficiency/gateway:latest
    ports:
      - "8080:8080"
    labels:
      - kompose.image-pull-policy=Always
      - kompose.hpa.cpu=70
      - kompose.hpa.memory=70
      - kompose.hpa.replicas.max=10
      - kompose.hpa.replicas.min=2
      - kompose.service.type=loadbalancer
      - kompose.service.healthcheck.liveness.http_get_port=8080
      - kompose.service.healthcheck.liveness.http_get_path=/actuator/health/liveness
      - kompose.service.healthcheck.readiness.http_get_port=8080
      - kompose.service.healthcheck.readiness.http_get_path=/actuator/health/readiness
      - kompose.service.healthcheck.readiness.start_period=8s
      - kompose.service.healthcheck.readiness.retries=3
      - kompose.service.healthcheck.readiness.timeout=5s
    environment:
      - EUREKA_URI=http://servicediscovery:8761/eureka
      - ZIPKIN_URI=http://zipkin:9411/
      - JAVA_TOOL_OPTIONS=-XX:ActiveProcessorCount=4 -XX:MaxDirectMemorySize=500M  #https://github.com/paketo-buildpacks/spring-boot/issues/11
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          memory: 1200M
        reservations:
          cpus: '0.5'
          memory: 1200M
    healthcheck: # without test --> will be provided by kompose.service.healthcheck.liveness
      start_period: 8s
      timeout: 10s
      retries: 5
    stop_grace_period: 30s

  servicediscovery:
    image: ghcr.io/tobias-pe/distributed-systems-energy-efficiency/servicediscovery:latest
    labels:
      - kompose.image-pull-policy=Always
      - kompose.service.type=loadbalancer
      - kompose.service.healthcheck.liveness.http_get_port=8761
      - kompose.service.healthcheck.liveness.http_get_path=/actuator/health/liveness
      - kompose.service.healthcheck.readiness.http_get_port=8761
      - kompose.service.healthcheck.readiness.http_get_path=/actuator/health/readiness
      - kompose.service.healthcheck.readiness.start_period=8s
      - kompose.service.healthcheck.readiness.retries=3
      - kompose.service.healthcheck.readiness.timeout=5s
    environment:
      - ZIPKIN_URI=http://zipkin:9411/
      - JAVA_TOOL_OPTIONS=-XX:ActiveProcessorCount=4 -XX:MaxDirectMemorySize=100M  #https://github.com/paketo-buildpacks/spring-boot/issues/11
    deploy:
      resources:
        limits:
          memory: 1000M
        reservations:
          cpus: '0.4'
          memory: 1000M
    ports:
      - "8761:8761"
    healthcheck: # without test --> will be provided by kompose.service.healthcheck.liveness
      start_period: 8s
      timeout: 10s
      retries: 5