include:
  - infrastructure-compose.yml

services:
  userservice:
    image: ghcr.io/tobias-pe/distributed-systems-energy-efficiency/userservice:latest
    labels:
      - kompose.hpa.cpu=80
      - kompose.hpa.memory=65
      - kompose.hpa.replicas.max=10
      - kompose.hpa.replicas.min=2
      - kompose.service.healthcheck.liveness.http_get_port=8081
      - kompose.service.healthcheck.liveness.http_get_path=/actuator/health/liveness
      - kompose.service.healthcheck.readiness.http_get_port=8081
      - kompose.service.healthcheck.readiness.http_get_path=/actuator/health/readiness
    environment:
      - EUREKA_URI=http://servicediscovery:8761/eureka
      - ZIPKIN_URI=http://zipkin:9411/
      - RABBITMQ_HOST=rabbitmq
      - POSTGRES_URI=jdbc:postgresql://userservice-db:5432/
      - JAVA_TOOL_OPTIONS=-XX:ActiveProcessorCount=4
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          memory: 1000M
        reservations:
          cpus: '1.0'
          memory: 1000M

  postservice:
    image: ghcr.io/tobias-pe/distributed-systems-energy-efficiency/postservice:latest
    labels:
      - kompose.hpa.cpu=70
      - kompose.hpa.memory=80
      - kompose.hpa.replicas.max=10
      - kompose.hpa.replicas.min=2
      - kompose.service.healthcheck.liveness.http_get_port=8082
      - kompose.service.healthcheck.liveness.http_get_path=/actuator/health/liveness
      - kompose.service.healthcheck.readiness.http_get_port=8082
      - kompose.service.healthcheck.readiness.http_get_path=/actuator/health/readiness
    environment:
      - EUREKA_URI=http://servicediscovery:8761/eureka
      - ZIPKIN_URI=http://zipkin:9411/
      - RABBITMQ_HOST=rabbitmq
      - POSTGRES_URI=jdbc:postgresql://postservice-db:5433/
      - JAVA_TOOL_OPTIONS=-XX:ActiveProcessorCount=4
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          memory: 1000M
        reservations:
          cpus: '1.0'
          memory: 1000M

  notificationservice:
    image: ghcr.io/tobias-pe/distributed-systems-energy-efficiency/notificationservice:latest
    labels:
      - kompose.hpa.cpu=80
      - kompose.hpa.memory=80
      - kompose.hpa.replicas.max=10
      - kompose.hpa.replicas.min=2
      - kompose.service.healthcheck.liveness.http_get_port=8083
      - kompose.service.healthcheck.liveness.http_get_path=/actuator/health/liveness
      - kompose.service.healthcheck.readiness.http_get_port=8083
      - kompose.service.healthcheck.readiness.http_get_path=/actuator/health/readiness
    environment:
      - EUREKA_URI=http://servicediscovery:8761/eureka
      - ZIPKIN_URI=http://zipkin:9411/
      - RABBITMQ_HOST=rabbitmq
      - POSTGRES_URI=jdbc:postgresql://notificationservice-db:5434/
      - JAVA_TOOL_OPTIONS=-XX:ActiveProcessorCount=4
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          memory: 1000M
        reservations:
          cpus: '1.0'
          memory: 1000M

  statisticservice:
    image: ghcr.io/tobias-pe/distributed-systems-energy-efficiency/statisticservice:latest
    labels:
      - kompose.hpa.cpu=80
      - kompose.hpa.memory=80
      - kompose.hpa.replicas.max=10
      - kompose.hpa.replicas.min=2
      - kompose.service.healthcheck.liveness.http_get_port=8084
      - kompose.service.healthcheck.liveness.http_get_path=/actuator/health/liveness
      - kompose.service.healthcheck.readiness.http_get_port=8084
      - kompose.service.healthcheck.readiness.http_get_path=/actuator/health/readiness
    environment:
      - EUREKA_URI=http://servicediscovery:8761/eureka
      - ZIPKIN_URI=http://zipkin:9411/
      - RABBITMQ_HOST=rabbitmq
      - POSTGRES_URI=jdbc:postgresql://statisticservice-db:5435/
      - JAVA_TOOL_OPTIONS=-XX:ActiveProcessorCount=4
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          memory: 1000M
        reservations:
          cpus: '1.0'
          memory: 1000M

  feedservice:
    image: ghcr.io/tobias-pe/distributed-systems-energy-efficiency/feedservice:latest
    labels:
      - kompose.hpa.cpu=70
      - kompose.hpa.memory=70
      - kompose.hpa.replicas.max=10
      - kompose.hpa.replicas.min=2
      - kompose.service.healthcheck.liveness.http_get_port=8085
      - kompose.service.healthcheck.liveness.http_get_path=/actuator/health/liveness
      - kompose.service.healthcheck.readiness.http_get_port=8085
      - kompose.service.healthcheck.readiness.http_get_path=/actuator/health/readiness
    environment:
      - EUREKA_URI=http://servicediscovery:8761/eureka
      - ZIPKIN_URI=http://zipkin:9411/
      - RABBITMQ_HOST=rabbitmq
      - POSTGRES_URI=jdbc:postgresql://feedservice-db:5436/
      - JAVA_TOOL_OPTIONS=-XX:ActiveProcessorCount=4
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          memory: 1000M
        reservations:
          cpus: '1.0'
          memory: 1000M

  gateway:
    image: ghcr.io/tobias-pe/distributed-systems-energy-efficiency/gateway:latest
    ports:
      - "8080:8080"
    labels:
      - kompose.hpa.cpu=70
      - kompose.hpa.memory=70
      - kompose.hpa.replicas.max=10
      - kompose.hpa.replicas.min=2
      - kompose.service.type=loadbalancer
      - kompose.service.healthcheck.liveness.http_get_port=8080
      - kompose.service.healthcheck.liveness.http_get_path=/actuator/health/liveness
      - kompose.service.healthcheck.readiness.http_get_port=8080
      - kompose.service.healthcheck.readiness.http_get_path=/actuator/health/readiness
    environment:
      - EUREKA_URI=http://servicediscovery:8761/eureka
      - ZIPKIN_URI=http://zipkin:9411/
      - JAVA_TOOL_OPTIONS=-XX:ActiveProcessorCount=4
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          memory: 1000M
        reservations:
          cpus: '1.0'
          memory: 1000M


  servicediscovery:
    image: ghcr.io/tobias-pe/distributed-systems-energy-efficiency/servicediscovery:latest
    labels:
      - kompose.service.type=loadbalancer
      - kompose.service.healthcheck.liveness.http_get_port=8761
      - kompose.service.healthcheck.liveness.http_get_path=/actuator/health/liveness
      - kompose.service.healthcheck.readiness.http_get_port=8761
      - kompose.service.healthcheck.readiness.http_get_path=/actuator/health/readiness
    environment:
      - ZIPKIN_URI=http://zipkin:9411/
      - JAVA_TOOL_OPTIONS=-XX:ActiveProcessorCount=4
    deploy:
      resources:
        limits:
          memory: 1000M
        reservations:
          cpus: '1.0'
          memory: 1000M
    ports:
      - "8761:8761"