version: '3.8'

include:
  - infrastructure-compose.yml

services:
  userservice:
    image: ghcr.io/tobias-pe/microservices_energyefficiency/userservice:latest
    environment:
      - EUREKA_URI=http://servicediscovery:8761/eureka
      - ZIPKIN_URI=http://zipkin:9411/
    deploy:
      mode: replicated
      replicas: 2

  gateway:
    image: ghcr.io/tobias-pe/microservices_energyefficiency/gateway:latest
    ports:
      - 8080:8080
    environment:
      - EUREKA_URI=http://servicediscovery:8761/eureka
      - ZIPKIN_URI=http://zipkin:9411/


  servicediscovery:
    image: ghcr.io/tobias-pe/microservices_energyefficiency/servicediscovery:latest
    environment:
      - ZIPKIN_URI=http://zipkin:9411/
    ports:
      - 8761:8761