version: '3.8'

services:
  mysql:
    image: mysql:8.3
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    labels:
      - kompose.service.type=loadbalancer
    ports:
      - "3306:3306"

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    labels:
      - kompose.service.type=loadbalancer
      - kompose.service.group=rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7.2
    container_name: redis
    labels:
      - kompose.service.type=loadbalancer
    ports:
      - "6379:6379"

  zipkin:
    image: openzipkin/zipkin:3
    container_name: zipkin
    labels:
      - kompose.service.type=loadbalancer
    ports:
      - "9411:9411"

  grafana:
    image: ghcr.io/tobias-pe/microservices_energyefficiency/grafana:latest
    build:
      dockerfile: docker/grafana/Dockerfile
      context: ..
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    labels:
      - kompose.service.type=loadbalancer
      - kompose.security-context.fsgroup=1000
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - 'grafana_data:/var/lib/grafana'

  prometheus:
    image: ghcr.io/tobias-pe/microservices_energyefficiency/prometheus:latest
    build:
      dockerfile: docker/prometheus/Dockerfile
      context: ..
    restart: unless-stopped
    labels:
      - kompose.service.type=loadbalancer
      - kompose.security-context.fsgroup=1000
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    ports:
      - "9090:9090"

  snmp-exporter:
    image: ghcr.io/tobias-pe/microservices_energyefficiency/snmp-exporter:latest
    build:
      dockerfile: docker/snmp-exporter/Dockerfile
      context: ..
    restart: unless-stopped
    labels:
      - kompose.security-context.fsgroup=1000
    ports:
      - "9116:9116"

volumes:
  mysql_data: {  }
  prometheus_data: {  }
  grafana_data: {  }
