version: '3.8'

services:
  mysql:
    image: mysql:8.3
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"

  zipkin:
    image: openzipkin/zipkin:3
    container_name: zipkin
    ports:
      - "9411:9411"

  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.7.0
    labels:
      - kompose.security-context.fsgroup=1000
      - kompose.volume.storage-class-name=nfs-csi
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /:/host:ro,rslave
    command:
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    restart: always
    deploy:
      mode: global

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    labels:
      - kompose.security-context.fsgroup=1000
      - kompose.volume.storage-class-name=nfs-csi
    restart: always
    deploy:
      mode: global

  grafana:
    image: ghcr.io/tobias-pe/microservices_energyefficiency/grafana:latest
    build:
      dockerfile: docker/grafana/Dockerfile
      context: ..
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    labels:
      - kompose.security-context.fsgroup=1000
      - kompose.volume.storage-class-name=nfs-csi
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - 'grafana_data:/var/lib/grafana'

  prometheus:
    image: ghcr.io/tobias-pe/microservices_energyefficiency/prometheus:latest
    build:
      dockerfile: docker/prometheus/Dockerfile
      context: ..
    container_name: prometheus
    restart: unless-stopped
    labels:
      - kompose.security-context.fsgroup=1000
      - kompose.volume.storage-class-name=nfs-csi
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    ports:
      - "9090:9090"

volumes:
  mysql_data: {  }
  prometheus_data: {  }
  grafana_data: {  }
