spring:
  application:
    name: userservice
  output:
    ansi:
      enabled: ALWAYS
  docker:
    compose:
      enabled: true
      file: docker/infrastructure-compose.yml
  datasource:
    username: myuser
    password: mypassword
    url: ${POSTGRES_URI:jdbc:postgresql://localhost:5432/}mydatabase

  jpa:
    hibernate:
      ddl-auto: update

server:
  forward-headers-strategy: framework
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URI:http://localhost:9411/}api/v2/spans
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true


