{
 "title": "Kepler Exporter Dashboard",
 "description": "Dashboard for Kepler Exporter",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kepler_container_package_joules_total, container_namespace)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kepler_container_package_joules_total{container_namespace=~\"$namespace\"},container_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Server PDU Watt Metric",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "cmcIIIVarValueInt", "legendFormat": "{{cmcIIIVarIndex}}" }
   ]
  },
  {
   "title": "Server PDU Watt Overall Comsumption (export)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "sum(cmcIIIVarValueInt)", "legendFormat": "{{cmcIIIVarIndex}}" }
   ]
  },
  {
   "title": "Power Consumption over the current Interval",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "Kepler container Joules Total in Namespace: \"$namespace\" (for export)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kepler_container_joules_total{container_namespace=~\"$namespace\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Pub Sub Rate",
   "type": "timeseries",
   "description": "Here you can get a feeling if the Queues are all consumed",
   "gridPos": { "h": 11, "w": 7, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(rabbitmq_published_total[1m])"
    },
    {
     "expr": "rate(rabbitmq_consumed_total[1m])"
    }
   ]
  },
  {
   "title": "Total Power Consumption (W) in Namespace: $namespace",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum(increase(kepler_container_joules_total{container_namespace=~\"$namespace\"}[100y]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Summed Node Power Consumption (W) in Namespace: $namespace",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "targets": [
    {
     "expr": "sum by (instance) (increase(kepler_container_joules_total{container_namespace=~\"$namespace\"}[100y]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Container Power Consumption in Namespace: \"$namespace\" with name: \"$container\" dram/package/other",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "targets": [
    {
     "expr": "sum by(container_name) (increase(kepler_container_dram_joules_total{container_namespace=~\"$namespace\", container_name=~\"$container\"}[100y]))",
     "legendFormat": "{{container_name}} - DRAM"
    },
    {
     "expr": "sum by(container_name) (increase(kepler_container_package_joules_total{container_namespace=~\"$namespace\", container_name=~\"$container\"}[100y]))",
     "legendFormat": "{{container_name}} - Package"
    },
    {
     "expr": "sum by(container_name) (increase(kepler_container_other_joules_total{container_namespace=~\"$namespace\", container_name=~\"$container\"}[100y]))",
     "legendFormat": "{{container_name}} - Other"
    }
   ]
  },
  {
   "title": "Pod Power Consumption in Namespace: \"$namespace\" with Container-Name: \"$container\" dram/package/other",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "targets": [
    {
     "expr": "sum by(pod_name) (increase(kepler_container_dram_joules_total{container_namespace=~\"$namespace\", container_name=~\"$container\"}[100y]))",
     "legendFormat": "{{pod_name}} - DRAM"
    },
    {
     "expr": "sum by(pod_name) (increase(kepler_container_package_joules_total{container_namespace=~\"$namespace\", container_name=~\"$container\"}[100y]))",
     "legendFormat": "{{pod_name}} - Package"
    },
    {
     "expr": "sum by(pod_name) (increase(kepler_container_other_joules_total{container_namespace=~\"$namespace\", container_name=~\"$container\"}[100y]))",
     "legendFormat": "{{pod_name}} - Other"
    }
   ]
  },
  {
   "title": "Usefull Work - Service Metrics (export)",
   "type": "timeseries",
   "description": "All prometheus metrics which symbolize usefull work: Some custom metrics & successfull http requests",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{error=\"none\", outcome!~\"SERVER_ERROR|UNKNOWN\"}"
    },
    {
     "expr": "feedservice_updated_preferences_counter_total"
    },
    {
     "expr": "notificationservice_created_notifications_counter_total"
    },
    {
     "expr": "trendservice_trend_updates_counter_total"
    }
   ]
  },
  {
   "title": "Summed Container Power Consumption (W) in Namespace: $namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "targets": [
    {
     "expr": "sum by(container_name, container_namespace) (increase(kepler_container_joules_total{container_namespace=~\"$namespace\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}