spring:
  application:
    name: servicediscovery
    output:
      ansi:
        enabled: ALWAYS
  docker:
    compose:
      enabled: true
      file: docker/infrastructure-compose.yml
      lifecycle-management: start-only

server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: "*"
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URI:http://localhost:9411/}api/v2/spans
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging.level.com.netflix:
  eureka: INFO
  discovery: INFO
