apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker/docker-compose.yml -o ./kubernetes/
    kompose.hpa.cpu: "80"
    kompose.hpa.memory: "70"
    kompose.hpa.replicas.max: "10"
    kompose.hpa.replicas.min: "2"
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: feedservice
  name: feedservice
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: feedservice
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./docker/docker-compose.yml -o ./kubernetes/
        kompose.hpa.cpu: "80"
        kompose.hpa.memory: "70"
        kompose.hpa.replicas.max: "10"
        kompose.hpa.replicas.min: "2"
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: feedservice
    spec:
      containers:
        - env:
            - name: EUREKA_URI
              value: http://servicediscovery:8761/eureka
            - name: JAVA_TOOL_OPTIONS
              value: -XX:ActiveProcessorCount=4
            - name: POSTGRES_URI
              value: jdbc:postgresql://feedservice-db:5436/
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: THC_PATH
              value: /actuator/health
            - name: THC_PORT
              value: "8085"
            - name: ZIPKIN_URI
              value: http://zipkin:9411/
          image: ghcr.io/tobias-pe/distributed-systems-energy-efficiency/feedservice:latest
          livenessProbe:
            exec:
              command:
                - /cnb/process/health-check
          name: feedservice
          resources:
            limits:
              memory: "1048576e3"
            requests:
              cpu: "1"
              memory: "1048576e3"
      restartPolicy: Always
