apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker/docker-compose.yml -o ./kubernetes/
    kompose.hpa.cpu: "70"
    kompose.hpa.memory: "70"
    kompose.hpa.replicas.max: "12"
    kompose.hpa.replicas.min: "2"
    kompose.image-pull-policy: Always
    kompose.service.healthcheck.liveness.http_get_path: /actuator/health/liveness
    kompose.service.healthcheck.liveness.http_get_port: "8085"
    kompose.service.healthcheck.readiness.http_get_path: /actuator/health/readiness
    kompose.service.healthcheck.readiness.http_get_port: "8085"
    kompose.service.healthcheck.readiness.retries: "3"
    kompose.service.healthcheck.readiness.start_period: 8s
    kompose.service.healthcheck.readiness.timeout: 5s
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: feedservice
  name: feedservice
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: feedservice
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./docker/docker-compose.yml -o ./kubernetes/
        kompose.hpa.cpu: "70"
        kompose.hpa.memory: "70"
        kompose.hpa.replicas.max: "12"
        kompose.hpa.replicas.min: "2"
        kompose.image-pull-policy: Always
        kompose.service.healthcheck.liveness.http_get_path: /actuator/health/liveness
        kompose.service.healthcheck.liveness.http_get_port: "8085"
        kompose.service.healthcheck.readiness.http_get_path: /actuator/health/readiness
        kompose.service.healthcheck.readiness.http_get_port: "8085"
        kompose.service.healthcheck.readiness.retries: "3"
        kompose.service.healthcheck.readiness.start_period: 8s
        kompose.service.healthcheck.readiness.timeout: 5s
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: feedservice
    spec:
      containers:
        - env:
            - name: EUREKA_URI
              value: http://servicediscovery:8761/eureka
            - name: JAVA_TOOL_OPTIONS
              value: -XX:ActiveProcessorCount=4 -XX:MaxDirectMemorySize=100M
            - name: POSTGRES_URI
              value: jdbc:postgresql://feedservice-db:5436/
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: REDIS_URI
              value: redis
            - name: ZIPKIN_URI
              value: http://zipkin:9411/
          image: ghcr.io/tobias-pe/distributed-systems-energy-efficiency/feedservice:02-resource-usage
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /actuator/health/liveness
              port: 8085
            initialDelaySeconds: 8
            timeoutSeconds: 10
          name: feedservice
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/readiness
              port: 8085
            initialDelaySeconds: 8
            timeoutSeconds: 5
          resources:
            limits:
              memory: "1258291200"
            requests:
              cpu: 550m
              memory: "1258291200"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
