apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker/docker-compose.yml -o ./kubernetes/
    kompose.hpa.cpu: "70"
    kompose.hpa.memory: "850"
    kompose.hpa.replicas.max: "10"
    kompose.service.type: loadbalancer
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: gateway
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./docker/docker-compose.yml -o ./kubernetes/
        kompose.hpa.cpu: "70"
        kompose.hpa.memory: "850"
        kompose.hpa.replicas.max: "10"
        kompose.service.type: loadbalancer
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: gateway
    spec:
      containers:
        - env:
            - name: EUREKA_URI
              value: http://servicediscovery:8761/eureka
            - name: JAVA_TOOL_OPTIONS
              value: -XX:ActiveProcessorCount=4
            - name: THC_PATH
              value: /actuator/health
            - name: THC_PORT
              value: "8080"
            - name: ZIPKIN_URI
              value: http://zipkin:9411/
          image: ghcr.io/tobias-pe/distributed-systems-energy-efficiency/gateway:latest
          livenessProbe:
            exec:
              command:
                - /cnb/process/health-check
          name: gateway
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: "1048576e3"
            requests:
              cpu: "2"
              memory: "1048576e3"
      restartPolicy: Always
