apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker/docker-compose.yml -o ./kubernetes/
    kompose.security-context.fsgroup: "1000"
    kompose.version: 1.32.0 (765fde254)
    kompose.volume.storage-class-name: nfs-csi
  labels:
    io.kompose.service: node-exporter
  name: node-exporter
spec:
  selector:
    matchLabels:
      io.kompose.service: node-exporter
  template:
    metadata:
      labels:
        io.kompose.network/docker-default: "true"
        io.kompose.service: node-exporter
    spec:
      containers:
        - args:
            - --path.rootfs=/host
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --collector.filesystem.ignored-mount-points
            - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($()|/)
          image: quay.io/prometheus/node-exporter:v1.7.0
          name: node-exporter
          volumeMounts:
            - mountPath: /host/proc
              name: node-exporter-claim0
              readOnly: true
            - mountPath: /host/sys
              name: node-exporter-claim1
              readOnly: true
            - mountPath: /rootfs
              name: node-exporter-claim2
              readOnly: true
            - mountPath: /host
              name: node-exporter-claim3
              readOnly: true
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
      volumes:
        - name: node-exporter-claim0
          persistentVolumeClaim:
            claimName: node-exporter-claim0
            readOnly: true
        - name: node-exporter-claim1
          persistentVolumeClaim:
            claimName: node-exporter-claim1
            readOnly: true
        - name: node-exporter-claim2
          persistentVolumeClaim:
            claimName: node-exporter-claim2
            readOnly: true
        - name: node-exporter-claim3
          persistentVolumeClaim:
            claimName: node-exporter-claim3
            readOnly: true
