apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker/docker-compose.yml -o ./kubernetes/
    kompose.service.type: loadbalancer
    kompose.version: 1.34.0 (cbf2835db)
    org.springframework.boot.ignore: "true"
  labels:
    io.kompose.service: notificationservice-db
  name: notificationservice-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: notificationservice-db
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./docker/docker-compose.yml -o ./kubernetes/
        kompose.service.type: loadbalancer
        kompose.version: 1.34.0 (cbf2835db)
        org.springframework.boot.ignore: "true"
      labels:
        io.kompose.service: notificationservice-db
    spec:
      containers:
        - args:
            - -c
            - max_connections=200
          env:
            - name: POSTGRES_DB
              value: notificationdatabase
            - name: POSTGRES_PASSWORD
              value: mypassword
            - name: POSTGRES_USER
              value: myuser
          image: postgres:16
          name: notificationservice-db
          ports:
            - containerPort: 5432
              protocol: TCP
      restartPolicy: Always
