apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker/docker-compose.yml -o ./kubernetes/
    kompose.service.type: loadbalancer
    kompose.version: 1.32.0 (765fde254)
    org.springframework.boot.ignore: "true"
  labels:
    io.kompose.service: postservice-db-tcp
  name: postservice-db
spec:
  ports:
    - name: "5433"
      port: 5433
      targetPort: 5432
  selector:
    io.kompose.service: postservice-db
  type: LoadBalancer
