apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker/docker-compose.yml -o ./kubernetes/
    kompose.service.type: loadbalancer
    kompose.version: 1.32.0 (765fde254)
    org.springframework.boot.ignore: "true"
  labels:
    io.kompose.service: postservice-db
  name: postservice-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postservice-db
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./docker/docker-compose.yml -o ./kubernetes/
        kompose.service.type: loadbalancer
        kompose.version: 1.32.0 (765fde254)
        org.springframework.boot.ignore: "true"
      labels:
        io.kompose.network/docker-default: "true"
        io.kompose.service: postservice-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: postdatabase
            - name: POSTGRES_PASSWORD
              value: mypassword
            - name: POSTGRES_USER
              value: myuser
          image: postgres:16
          name: postservice-db
          ports:
            - containerPort: 5432
              hostPort: 5433
              protocol: TCP
      restartPolicy: Always
