apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker/docker-compose.yml -o ./kubernetes/
    kompose.service.group: rabbitmq
    kompose.service.type: loadbalancer
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: rabbitmq-tcp
  name: rabbitmq
spec:
  ports:
    - name: "5672"
      port: 5672
      targetPort: 5672
    - name: "15672"
      port: 15672
      targetPort: 15672
  selector:
    io.kompose.service: rabbitmq
  type: LoadBalancer
