apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker/docker-compose.yml -o ./kubernetes/
    kompose.service.type: loadbalancer
    kompose.version: 1.32.0 (765fde254)
    org.springframework.boot.ignore: "true"
  labels:
    io.kompose.service: statisticservice-db-tcp
  name: statisticservice-db
spec:
  ports:
    - name: "5435"
      port: 5435
      targetPort: 5432
  selector:
    io.kompose.service: statisticservice-db
  type: LoadBalancer
