apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker/docker-compose.yml -o ./kubernetes/
    kompose.service.type: loadbalancer
    kompose.version: 1.34.0 (cbf2835db)
    org.springframework.boot.ignore: "true"
  labels:
    io.kompose.service: userservice-db-tcp
  name: userservice-db
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: userservice-db
  type: LoadBalancer
