apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker/docker-compose.yml -o ./kubernetes/
    kompose.service.type: loadbalancer
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: zipkin
  name: zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zipkin
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./docker/docker-compose.yml -o ./kubernetes/
        kompose.service.type: loadbalancer
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/docker-default: "true"
        io.kompose.service: zipkin
    spec:
      containers:
        - image: openzipkin/zipkin:3
          name: zipkin
          ports:
            - containerPort: 9411
              hostPort: 9411
              protocol: TCP
      restartPolicy: Always
