# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'my-project'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 15s

    static_configs:
         - targets: ['localhost:9090']


  - job_name: 'eureka'

    # Scrape Eureka itself to discover new services.
    eureka_sd_configs:
      - server: http://servicediscovery:8761/eureka
    relabel_configs:
      - source_labels: [ __meta_eureka_app_name ]
        target_label: application
      - replacement: /actuator/prometheus
        target_label: __metrics_path__
      - source_labels: [ __address__ ]
        target_label: instance

  - job_name: 'snmp'
    scrape_interval: 3s
    static_configs:
      - targets:
          - 10.28.1.126
    metrics_path: /snmp
    params:
      auth: [ public_v2 ]
      module: [ if_power ]
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9116

  - job_name: 'snmp-exporter'
    static_configs:
      - targets: [ 'snmp-exporter:9116' ]