spring:
  application:
    name: feedservice
  output:
    ansi:
      enabled: ALWAYS
  docker:
    compose:
      enabled: true
      file: docker/infrastructure-compose.yml
      lifecycle-management: start-only
  datasource:
    username: myuser
    password: mypassword
    url: ${POSTGRES_URI:jdbc:postgresql://localhost:5436/}feeddatabase
  jpa:
    hibernate:
      ddl-auto: update
    #show-sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
  lifecycle:
    timeout-per-shutdown-phase: 20s
  cache:
    type: redis
    redis:
      time-to-live: 60000
  data:
    redis:
      host: ${REDIS_URI:localhost}
      port: 6379

server:
  forward-headers-strategy: framework
  port: 8085
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: "*"
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URI:http://localhost:9411/}api/v2/spans
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true


